FROM nginx:latest

# Eliminar la configuración predeterminada de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar nuestro archivo de configuración
#COPY nginx.conf /etc/nginx/conf.d/

# Crear directorios de archivos estáticos y media
RUN mkdir -p /app/staticfiles /app/media

# Exponer el puerto 80
EXPOSE 80
