services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: odoodjango
      POSTGRES_USER: freddy
      POSTGRES_PASSWORD: 2k23R&Fjdn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    command: >
      postgres -c listen_addresses='*'
    networks:
      - shared_network

  web:
    build: .
    container_name: django_app
    depends_on:
      - db
    environment:
      POSTGRES_DB: odoodjango
      POSTGRES_USER: freddy
      POSTGRES_PASSWORD: 2k23R&Fjdn
      POSTGRES_HOST: db  
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: ["gunicorn", "odoodjango.wsgi:application", "--bind", "0.0.0.0:8000"]
    networks:
      - shared_network

  adminer:
    image: adminer
    container_name: adminer_db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - shared_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - shared_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  shared_network:
    external: true
